#!/bin/bash
# Builds Tokes and assembles build/Tokes.app. Pass --run to (re)launch it.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT=$(pwd)

swift build -c release

APP=build/Tokes.app
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp .build/release/Tokes "$APP/Contents/MacOS/Tokes"
cp scripts/Info.plist "$APP/Contents/Info.plist"

# App icon. actool derives BOTH shipping forms from the one Icon Composer
# package: Assets.car (full-bleed, masked by macOS 26) and Tokes.icns (legacy,
# inset to ~83.6% of canvas, for macOS 14/15). Never pass an .appiconset
# alongside it — when a .icon is present under the same --app-icon name, actool
# ignores the appiconset silently and the output looks correct either way.
# The package is generated by the design practice; see packaging/icon/README.md.
MIN_OS=$(/usr/libexec/PlistBuddy -c 'Print :LSMinimumSystemVersion' scripts/Info.plist)
ICON_PLIST=$(mktemp -t tokes-icon-plist)
# actool runs as a persistent XPC service that can carry a stale working
# directory between invocations, so every path handed to it must be absolute.
if ! ACTOOL_OUT=$(xcrun actool "$ROOT/packaging/icon/Tokes.icon" \
        --compile "$ROOT/$APP/Contents/Resources" --app-icon Tokes --include-all-app-icons \
        --output-partial-info-plist "$ICON_PLIST" \
        --platform macosx --target-device mac --minimum-deployment-target "$MIN_OS" \
        --output-format human-readable-text --errors --warnings 2>&1); then
    echo "$ACTOOL_OUT" >&2
    rm -f "$ICON_PLIST"
    exit 1
fi

# Merge actool's generated icon keys into the bundle's Info.plist.
for key in CFBundleIconFile CFBundleIconName; do
    value=$(/usr/libexec/PlistBuddy -c "Print :$key" "$ICON_PLIST")
    /usr/libexec/PlistBuddy -c "Add :$key string $value" "$APP/Contents/Info.plist"
done
rm -f "$ICON_PLIST"

codesign --force -s - "$APP"

echo "Built $APP"

if [[ "${1:-}" == "--run" ]]; then
    pkill -x Tokes 2>/dev/null || true
    sleep 0.3
    open "$APP"
    echo "Launched Tokes"
fi
