#!/bin/bash
# Builds Tokes and assembles an app bundle.
#
# Usage:
#   scripts/build.sh [--run]                     # direct build -> build/Tokes.app
#   scripts/build.sh --app-store [--sign ID]     # sandboxed build -> build/appstore/Tokes.app
#
# The two flavors are separate artifacts with separate scratch directories, and
# the App Store one compiles with -DTOKES_APP_STORE so the credential readers
# that reach outside the container are not in the binary at all. See
# docs/APP-STORE-COMPLIANCE.md; scripts/verify-appstore.sh proves it afterwards.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT=$(pwd)

FLAVOR=direct
SIGN_IDENTITY="-"
UNIVERSAL=""
RUN=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --app-store) FLAVOR=appstore; shift ;;
        --sign) SIGN_IDENTITY="$2"; shift 2 ;;
        --universal) UNIVERSAL=1; shift ;;
        --run) RUN=1; shift ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

if [[ "$FLAVOR" == appstore ]]; then
    SCRATCH=.build-appstore
    APP=build/appstore/Tokes.app
    ENTITLEMENTS="$ROOT/packaging/appstore/Tokes.entitlements"
    SWIFT_FLAGS=(-Xswiftc -DTOKES_APP_STORE)
else
    SCRATCH=.build
    APP=build/Tokes.app
    ENTITLEMENTS=""
    SWIFT_FLAGS=()
fi

# Universal for both flavors. Apple is retiring Intel *app* support, not
# universal binaries — Rosetta never touches a universal build, since the arm64
# slice runs natively. macOS 27 drops Intel Macs, but LSMinimumSystemVersion is
# 14.0 and Sonoma/Sequoia run on plenty of 2017-2020 Intel hardware whose owners
# can never move past macOS 26. At a 14.0 target, dropping x86_64 sheds current
# users, not legacy ones. Costs ~1 MB and ~18 s. Revisit when the deployment
# target passes 26, at which point no supported Mac can execute x86_64 anyway.
UNIVERSAL=${UNIVERSAL:-1}

ARCH_FLAGS=()
[[ -n "$UNIVERSAL" ]] && ARCH_FLAGS=(--arch arm64 --arch x86_64)

# ${a[@]+"${a[@]}"} rather than "${a[@]}": /bin/bash here is 3.2, where an empty
# array expansion trips `set -u`.
BUILD_ARGS=(-c release --scratch-path "$SCRATCH"
            ${ARCH_FLAGS[@]+"${ARCH_FLAGS[@]}"} ${SWIFT_FLAGS[@]+"${SWIFT_FLAGS[@]}"})

swift build "${BUILD_ARGS[@]}"
BIN_DIR=$(swift build "${BUILD_ARGS[@]}" --show-bin-path)

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN_DIR/Tokes" "$APP/Contents/MacOS/Tokes"
cp scripts/Info.plist "$APP/Contents/Info.plist"

# App icon. actool derives BOTH shipping forms from the one Icon Composer
# package: Assets.car (full-bleed, masked by macOS 26) and Tokes.icns (legacy,
# inset to ~83.6% of canvas, for macOS 14/15). Never pass an .appiconset
# alongside it — when a .icon is present under the same --app-icon name, actool
# ignores the appiconset silently and the output looks correct either way.
# The package is generated by the design practice; see packaging/icon/README.md.
MIN_OS=$(/usr/libexec/PlistBuddy -c 'Print :LSMinimumSystemVersion' scripts/Info.plist)
ICON_PLIST=$(mktemp -t tokes-icon-plist)
# actool runs as a persistent XPC service that can carry a stale working
# directory between invocations, so every path handed to it must be absolute.
if ! ACTOOL_OUT=$(xcrun actool "$ROOT/packaging/icon/Tokes.icon" \
        --compile "$ROOT/$APP/Contents/Resources" --app-icon Tokes --include-all-app-icons \
        --output-partial-info-plist "$ICON_PLIST" \
        --platform macosx --target-device mac --minimum-deployment-target "$MIN_OS" \
        --output-format human-readable-text --errors --warnings 2>&1); then
    echo "$ACTOOL_OUT" >&2
    rm -f "$ICON_PLIST"
    exit 1
fi

# Merge actool's generated icon keys into the bundle's Info.plist.
for key in CFBundleIconFile CFBundleIconName; do
    value=$(/usr/libexec/PlistBuddy -c "Print :$key" "$ICON_PLIST")
    /usr/libexec/PlistBuddy -c "Add :$key string $value" "$APP/Contents/Info.plist"
done
rm -f "$ICON_PLIST"

if [[ "$FLAVOR" == appstore ]]; then
    # App Store Connect validates the build-provenance keys Xcode normally
    # stamps in. A SwiftPM-assembled bundle has to write them itself or upload
    # fails with "Invalid bundle" long before review ever sees it.
    # awk, never `head -1`: under `set -o pipefail` head closes the pipe after
    # one line and xcodebuild takes SIGPIPE writing its second — racily, on
    # buffer timing — so the script died here with exit 141 right after
    # SwiftPM printed "Build complete!", leaving an unsigned, key-less bundle.
    # That race, not the caller's redirection, was the intermittent 141.
    XCODE_VER=$(xcodebuild -version | awk 'NR==1{print $2}')
    XCODE_BUILD=$(xcodebuild -version | awk 'NR==2{print $3}')
    SDK_VER=$(xcrun --show-sdk-version --sdk macosx)
    SDK_BUILD=$(xcrun --show-sdk-build-version --sdk macosx)
    # DTXcode is the version with dots removed and zero-padded: 26.6 -> 2660.
    DTXCODE=$(awk -F. '{printf "%d%d%d", $1, $2, ($3 == "" ? 0 : $3)}' <<<"$XCODE_VER")
    add_plist() { /usr/libexec/PlistBuddy -c "Add :$1 string $2" "$APP/Contents/Info.plist"; }
    add_plist DTCompiler "com.apple.compilers.llvm.clang.1_0"
    add_plist DTPlatformName "macosx"
    add_plist DTPlatformVersion "$SDK_VER"
    add_plist DTPlatformBuild "$SDK_BUILD"
    add_plist DTSDKName "macosx$SDK_VER"
    add_plist DTSDKBuild "$SDK_BUILD"
    add_plist DTXcode "$DTXCODE"
    add_plist DTXcodeBuild "$XCODE_BUILD"
    add_plist BuildMachineOSBuild "$(sw_vers -buildVersion)"

    # Only a real signing identity gets the provisioning profile and the
    # team-scoped entitlements. An ad-hoc build deliberately stays account-free:
    # that is what lets scripts/verify-appstore.sh launch it and exercise the
    # sandbox with no Apple certificates at all. Embedding a Mac App Store
    # profile would make launchd refuse it locally (POSIX 163).
    PROFILE=packaging/appstore/embedded.provisionprofile
    SIGN_ENTITLEMENTS="$ENTITLEMENTS"
    if [[ "$SIGN_IDENTITY" == "-" ]]; then
        :
    elif [[ -f "$PROFILE" ]]; then
        cp "$PROFILE" "$APP/Contents/embedded.provisionprofile"

        # The team-scoped entitlements are derived from the profile rather than
        # committed, so packaging/appstore/Tokes.entitlements stays team-neutral
        # and an ad-hoc local audit build (which has no profile) still runs.
        # Without these, upload succeeds but warns 90886 and the build is not
        # eligible for TestFlight: the profile carries an application-identifier
        # that the signature doesn't.
        MERGED=$(mktemp -t tokes-entitlements).plist
        /usr/bin/python3 - "$PROFILE" "$ENTITLEMENTS" "$MERGED" <<'EOF'
import plistlib, subprocess, sys
profile, base, out = sys.argv[1:4]
decoded = subprocess.run(["security", "cms", "-D", "-i", profile],
                         capture_output=True, check=True).stdout
p = plistlib.loads(decoded)
e = plistlib.load(open(base, "rb"))
pe = p.get("Entitlements", {})
# macOS profiles spell it com.apple.application-identifier; iOS uses the bare
# form. Checking only one silently drops it and the upload warns 90886.
appid = pe.get("com.apple.application-identifier") or pe.get("application-identifier")
if appid:
    e["com.apple.application-identifier"] = appid
if "com.apple.developer.team-identifier" in pe:
    e["com.apple.developer.team-identifier"] = pe["com.apple.developer.team-identifier"]
plistlib.dump(e, open(out, "wb"))
print("  entitlements: %s" % ", ".join(sorted(e)))
EOF
        SIGN_ENTITLEMENTS="$MERGED"
    else
        echo "warning: $PROFILE missing — App Store upload will be rejected." >&2
    fi

    codesign --force --entitlements "$SIGN_ENTITLEMENTS" -s "$SIGN_IDENTITY" "$APP"
    [[ "$SIGN_ENTITLEMENTS" != "$ENTITLEMENTS" ]] && rm -f "$SIGN_ENTITLEMENTS"
else
    codesign --force -s "$SIGN_IDENTITY" "$APP"
fi

echo "Built $APP ($FLAVOR, $(lipo -archs "$APP/Contents/MacOS/Tokes"))"

if [[ -n "$RUN" ]]; then
    pkill -x Tokes 2>/dev/null || true
    sleep 0.3
    open "$APP"
    echo "Launched Tokes"
fi
